model_type: yolov8s.pt
pretrained: True
seed: 0
imgsz: 640 
batch: 4
epochs: 1
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.001  # learning rate 
name: 'yolov8s_exp_v3' # experiment name
